spring:
  kafka:
    bootstrap-servers: localhost:9001, localhost:9002, localhost:9003
    producer:
      retries: 3
      acks: all
    consumer:
      properties:
        group:
          id: defaultConsumerGroup
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
    listener:
      missing-topics-fatal: false